# Generated by Django 4.2.5 on 2024-06-01 10:34

from django.db import migrations, models
import django.db.models.deletion
import helpers.model_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("autho", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "idx",
                    helpers.model_fields.IDXField(
                        blank=True, editable=False, length=8, max_length=15, unique=True
                    ),
                ),
                (
                    "created_date",
                    helpers.model_fields.CreatedDateField(
                        db_index=True, editable=False
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("product_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "dry_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in grams", max_digits=10
                    ),
                ),
                (
                    "wet_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in grams", max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                ("production_date", models.DateField(blank=True, null=True)),
                ("packing_date", models.DateField(blank=True, null=True)),
                ("number_of_units", models.IntegerField()),
                (
                    "wet_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="autho.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="stock.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
