# Generated by Django 4.2.5 on 2024-06-01 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("autho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "idx",
                    helpers.model_fields.IDXField(
                        blank=True, editable=False, length=8, max_length=15, unique=True
                    ),
                ),
                (
                    "created_date",
                    helpers.model_fields.CreatedDateField(
                        db_index=True, editable=False
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lead_time", models.IntegerField(help_text="lead time in days")),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
    ]
