# Generated by Django 4.2.5 on 2023-09-26 17:27

from django.db import migrations, models
import helpers.model_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "idx",
                    helpers.model_fields.IDXField(
                        blank=True, editable=False, length=8, max_length=15, unique=True
                    ),
                ),
                (
                    "created_date",
                    helpers.model_fields.CreatedDateField(
                        db_index=True, editable=False
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "unique_together": {("name", "method")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "idx",
                    helpers.model_fields.IDXField(
                        blank=True, editable=False, length=8, max_length=15, unique=True
                    ),
                ),
                (
                    "created_date",
                    helpers.model_fields.CreatedDateField(
                        db_index=True, editable=False
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("precedence", models.IntegerField(default=0)),
                ("badge_url", models.URLField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="permission.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
